--
-- Copyright 2024-2026 the original author or authors.
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--      http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

-- H2 stub for V6 (Row-Level Security). H2 does not support PostgreSQL RLS; the service-layer
-- org_id filtering (Phase A) and org-scoped storage namespaces (Phase F1) provide isolation in
-- the H2/dev profile. RLS is enforced only on PostgreSQL (see postgresql/V6__row_level_security.sql).
-- This empty migration keeps Flyway version parity between profiles.
